import type { Industry, IconName, FAQ } from "./types";

type Seed = {
  slug: string; name: string; icon: IconName; headline: string; intro: string; answer: string;
  challenges: [string, string][]; solutions: [string, string, string?][]; features: string[];
  useCases: [string, string][]; benefits: string[]; workflow: string[]; technology?: string[];
  faqs?: FAQ[]; relatedServices: string[]; relatedProducts: string[]; keyword: string;
};

const baseTech = ["Web applications (Next.js, React)", "Mobile apps (React Native, Flutter)", "APIs (FastAPI, Django)", "PostgreSQL", "AI & LLM integration", "Cloud hosting & backups"];

function build(s: Seed): Industry {
  return {
    slug: s.slug,
    name: s.name,
    icon: s.icon,
    seoTitle: `${s.keyword} | FairBazaar`,
    metaDescription: `${s.intro.split(". ")[0]}. FairBazaar builds ${s.name.toLowerCase()} software, automation and AI solutions.`.slice(0, 158),
    headline: s.headline,
    intro: s.intro,
    answer: { question: `What software does a ${s.name.toLowerCase()} business need?`, text: s.answer },
    challenges: s.challenges.map(([title, text]) => ({ title, text })),
    solutions: s.solutions.map(([title, text, href]) => ({ title, text, href })),
    features: s.features,
    technology: s.technology ?? baseTech,
    useCases: s.useCases.map(([title, text]) => ({ title, text })),
    benefits: s.benefits,
    workflow: s.workflow,
    faqs: [
      ...(s.faqs ?? []),
      { q: `Does FairBazaar build custom software for ${s.name.toLowerCase()}?`, a: `Yes. We design and build ${s.name.toLowerCase()} software around your specific workflows, and can combine our CRM, ERP, HRMS and AI platforms with custom modules.` },
      { q: "How long does implementation take?", a: "A focused first release typically takes 8–14 weeks after discovery. Larger platforms are delivered in phases so your team benefits early." },
    ],
    relatedServices: s.relatedServices,
    relatedProducts: s.relatedProducts,
  };
}

export const industries: Industry[] = [
  build({
    slug: "healthcare", name: "Healthcare", icon: "heart", keyword: "Healthcare Software Development",
    headline: "Technology for Clinics, Hospitals and Care Providers",
    intro: "Healthcare teams spend too much time on scheduling, paperwork and follow-ups. We build secure systems for appointments, patient records, billing and staff management so care teams can focus on patients.",
    answer: "Healthcare organisations typically need appointment scheduling, patient records, billing, pharmacy or inventory tracking, staff attendance and rostering, and patient communication. Connecting these in one secure system reduces administrative load, prevents double bookings and gives administrators real-time operational visibility.",
    challenges: [["Appointment chaos", "Phone-based booking, no-shows and double bookings."], ["Scattered records", "Patient history split across paper files and systems."], ["Staff rostering", "Shifts, attendance and payroll for clinical staff are complex."], ["Data sensitivity", "Health data requires strict access control and audit."]],
    solutions: [["Appointment & patient management", "Online booking, reminders, patient profiles and visit history.", "/services/custom-software-development"], ["Clinic ERP", "Billing, pharmacy stock and consumables tracking.", "/products/erp"], ["Healthcare HRMS", "Shift rostering, attendance and payroll for staff.", "/products/hrms"], ["AI patient assistant", "Answers FAQs, books appointments and sends reminders.", "/products/ai-agents"]],
    features: ["Online appointment booking", "Automated SMS/WhatsApp reminders", "Patient records with role-based access", "Billing and receipts", "Pharmacy & consumables inventory", "Staff rostering", "Audit logs"],
    useCases: [["Multi-doctor clinic", "Centralised scheduling and patient history across doctors."], ["Diagnostic centre", "Test booking, sample tracking and report delivery."], ["Hospital operations", "Staff attendance, departments and inventory in one view."]],
    benefits: ["Fewer no-shows", "Less front-desk workload", "Secure, auditable records", "Operational visibility"],
    workflow: ["Patient books online", "Reminder sent", "Check-in at reception", "Consultation recorded", "Bill generated", "Follow-up scheduled"],
    relatedServices: ["custom-software-development", "ai-development", "mobile-app-development"], relatedProducts: ["hrms", "ai-agents", "erp"],
  }),
  build({
    slug: "education", name: "Education", icon: "graduation", keyword: "Education Software Development",
    headline: "Digital Platforms for Schools, Colleges and Training Institutes",
    intro: "Educational institutions manage admissions, fees, attendance, courses and communication across many stakeholders. We build platforms that connect students, parents, faculty and administrators.",
    answer: "Educational institutions typically need admission and enquiry management, student information systems, fee collection, attendance, timetables, learning content delivery, examinations and parent communication. An integrated platform reduces administrative work and gives leadership a clear view of enrolment, fees and academic performance.",
    challenges: [["Admission enquiries", "Leads from many sources tracked in registers."], ["Fee follow-ups", "Manual tracking of dues and receipts."], ["Communication", "Parents and students updated through scattered channels."], ["Staff management", "Faculty attendance, leave and payroll."]],
    solutions: [["Admission CRM", "Track enquiries from first contact to enrolment.", "/products/crm"], ["Student management system", "Profiles, attendance, fees, exams and reports.", "/services/custom-software-development"], ["Learning platform", "Courses, content, assessments and progress.", "/services/web-development"], ["Faculty HRMS", "Attendance, leave and payroll for staff.", "/products/hrms"]],
    features: ["Enquiry & admission pipeline", "Online fee payments", "Attendance tracking", "Timetables", "Exams & report cards", "Parent app", "AI study assistant"],
    useCases: [["Coaching institute", "Admission CRM with batch management and fee tracking."], ["School", "Student information system with parent app."], ["Training academy", "Online courses with assessments and certificates."]],
    benefits: ["Higher enquiry conversion", "Faster fee collection", "Better parent engagement", "Less paperwork"],
    workflow: ["Enquiry captured", "Counselling follow-up", "Admission confirmed", "Fees collected", "Attendance & exams tracked", "Reports shared with parents"],
    relatedServices: ["web-development", "mobile-app-development", "crm-development"], relatedProducts: ["crm", "lead-management", "hrms"],
  }),
  build({
    slug: "agriculture", name: "Agriculture", icon: "sprout", keyword: "Agriculture Software Development",
    headline: "Digital Tools for Agribusiness, Farm Operations and Rural Supply Chains",
    intro: "Agriculture businesses coordinate farmers, field staff, dealers, procurement and inventory across wide geographies. We build field-ready apps and back-office systems that work in real rural conditions.",
    answer: "Agriculture businesses typically need farmer and field data collection, procurement tracking, dealer and distributor management, inventory for inputs and produce, field staff attendance with location verification, and advisory communication. Mobile-first, offline-capable software is essential because connectivity in rural areas is inconsistent.",
    challenges: [["Field visibility", "Hard to verify field staff visits and activities."], ["Procurement records", "Farmer transactions recorded on paper."], ["Dealer networks", "Orders and credit across many dealers."], ["Connectivity", "Unreliable mobile networks in rural areas."]],
    solutions: [["Field workforce app", "GPS attendance, visit logs and farmer data collection with offline sync.", "/services/mobile-app-development"], ["Procurement & inventory", "Track purchases, grading, storage and dispatch.", "/products/inventory-management"], ["Dealer management", "Orders, schemes and credit for input dealers.", "/products/erp"], ["Farmer advisory", "Multilingual AI assistant for crop and scheme queries.", "/products/ai-agents"]],
    features: ["Offline-first mobile app", "Location-verified field visits", "Farmer database", "Procurement & grading", "Warehouse inventory", "Dealer orders", "Regional language support"],
    useCases: [["Agri-input company", "Dealer ordering and field sales tracking."], ["Producer organisation", "Member records, procurement and payments."], ["Agri-processing unit", "Procurement to inventory to dispatch."]],
    benefits: ["Verified field activity", "Digital farmer records", "Better inventory control", "Faster dealer operations"],
    workflow: ["Field officer checks in", "Farmer visit recorded offline", "Data syncs when online", "Procurement logged", "Stock updated", "Management dashboard refreshed"],
    relatedServices: ["mobile-app-development", "erp-development", "digital-transformation"], relatedProducts: ["hrms", "inventory-management", "erp"],
  }),
  build({
    slug: "retail", name: "Retail", icon: "store", keyword: "Retail Software Development",
    headline: "Connected Commerce for Stores, Chains and Online Retail",
    intro: "Retailers need stock, sales, customers and staff connected across stores and online channels. We build retail systems that keep inventory accurate and customers coming back.",
    answer: "Retail businesses typically need point-of-sale integration, multi-location inventory, e-commerce, customer and loyalty management, purchasing, and staff attendance. Connecting store and online channels gives accurate stock visibility, prevents lost sales and enables personalised marketing.",
    challenges: [["Stock mismatch", "Store and online stock that don't agree."], ["Customer retention", "No customer data for loyalty or offers."], ["Multi-store control", "Limited visibility across locations."], ["Staff scheduling", "Shifts and attendance across stores."]],
    solutions: [["Retail ERP & inventory", "Multi-store stock, transfers and reorders.", "/products/inventory-management"], ["E-commerce", "Online store synced with store inventory.", "/services/web-development"], ["Customer CRM & loyalty", "Profiles, purchase history and campaigns.", "/products/crm"], ["AI shopping assistant", "Product Q&A and order status on WhatsApp.", "/products/ai-agents"]],
    features: ["Multi-store inventory", "Online store", "Loyalty programme", "Purchase management", "Store staff HRMS", "Sales dashboards"],
    useCases: [["Retail chain", "Central inventory and store transfers."], ["D2C brand", "E-commerce with order and customer management."], ["Distributor", "B2B ordering portal for retailers."]],
    benefits: ["Accurate stock", "Repeat customers", "Multi-store visibility", "Fewer stockouts"],
    workflow: ["Customer purchases", "Stock deducted", "Loyalty points added", "Reorder triggered", "Transfer or purchase", "Sales reports updated"],
    relatedServices: ["web-development", "erp-development", "crm-development"], relatedProducts: ["inventory-management", "crm", "erp"],
  }),
  build({
    slug: "manufacturing", name: "Manufacturing", icon: "factory", keyword: "Manufacturing ERP & Software",
    headline: "From Raw Material to Dispatch, Fully Visible",
    intro: "Manufacturers juggle production planning, inventory, purchasing, quality, workforce and dispatch. We build manufacturing ERP and shop-floor systems that connect them.",
    answer: "Manufacturers typically need production planning, bill of materials, raw material and finished goods inventory, purchasing, quality checks, workforce attendance and shift management, and dispatch. An integrated ERP connects these so managers can see order status, material availability and labour costs in real time.",
    challenges: [["Production visibility", "Order status known only by asking the floor."], ["Material planning", "Shortages or excess raw material."], ["Workforce", "Shift attendance and contract labour tracking."], ["Quality records", "Inspection results on paper."]],
    solutions: [["Manufacturing ERP", "BOM, work orders, inventory and dispatch.", "/products/erp"], ["Shop-floor app", "Job progress and quality checks from tablets.", "/services/mobile-app-development"], ["Workforce HRMS", "Shifts, attendance and payroll for plant staff.", "/products/hrms"], ["Process automation", "Approvals and alerts across departments.", "/products/business-automation"]],
    features: ["Bill of materials", "Work orders", "Raw material & FG inventory", "Purchase orders", "Quality checks", "Shift attendance", "Dispatch & invoicing"],
    useCases: [["Engineering unit", "Job-work tracking and material planning."], ["Food processing", "Batch tracking and expiry management."], ["Component supplier", "Customer schedules and dispatch planning."]],
    benefits: ["Real-time production status", "Lower material waste", "Accurate labour costs", "Traceable quality"],
    workflow: ["Customer order received", "Material availability checked", "Work order released", "Production progress updated", "Quality inspected", "Dispatched and invoiced"],
    relatedServices: ["erp-development", "custom-software-development", "business-automation"], relatedProducts: ["erp", "inventory-management", "hrms"],
  }),
  build({
    slug: "real-estate", name: "Real Estate", icon: "building", keyword: "Real Estate CRM & Software",
    headline: "Sell, Lease and Manage Properties With Less Friction",
    intro: "Real estate businesses depend on fast lead response, site visit coordination and long sales cycles. We build CRMs, portals and apps for developers, brokers and property managers.",
    answer: "Real estate businesses typically need lead management with fast response, inventory of units and availability, site visit scheduling, booking and payment tracking, channel partner management, and customer portals. A real estate CRM connects marketing leads to bookings and gives management a live view of inventory and collections.",
    challenges: [["Slow lead response", "Portal and ad leads not followed up quickly."], ["Unit inventory", "Availability tracked in spreadsheets."], ["Channel partners", "Broker leads and commissions."], ["Collections", "Payment milestones tracked manually."]],
    solutions: [["Real estate CRM", "Leads, site visits, bookings and follow-ups.", "/products/crm"], ["Inventory & booking", "Live unit availability and booking workflow.", "/services/custom-software-development"], ["Customer portal", "Documents, payments and construction updates.", "/services/web-development"], ["AI sales assistant", "Instant replies and site visit booking.", "/products/ai-agents"]],
    features: ["Multi-source lead capture", "Site visit scheduling", "Unit inventory", "Booking & payment milestones", "Channel partner portal", "Customer portal"],
    useCases: [["Developer", "Project-wise inventory and sales pipeline."], ["Brokerage", "Lead distribution and commission tracking."], ["Property manager", "Tenants, rent and maintenance requests."]],
    benefits: ["Faster lead response", "Accurate availability", "Better collection tracking", "Transparent partner management"],
    workflow: ["Lead arrives", "Auto-assigned & called", "Site visit booked", "Unit reserved", "Booking confirmed", "Payment milestones tracked"],
    relatedServices: ["crm-development", "web-development", "ai-development"], relatedProducts: ["crm", "lead-management", "ai-agents"],
  }),
  build({
    slug: "hospitality", name: "Hospitality", icon: "hotel", keyword: "Hospitality Software Development",
    headline: "Guest Experiences and Operations, Connected",
    intro: "Hotels, restaurants and travel businesses need reservations, guest communication, housekeeping and staff management working together.",
    answer: "Hospitality businesses typically need reservation and booking management, guest communication, housekeeping and maintenance workflows, inventory for kitchens and supplies, staff rostering and attendance, and guest feedback. Integrated systems reduce response times and improve guest satisfaction.",
    challenges: [["Booking fragmentation", "Reservations from many channels."], ["Guest communication", "Manual confirmations and requests."], ["Housekeeping", "Room status not updated in real time."], ["Shift staff", "Rostering and attendance."]],
    solutions: [["Booking system", "Direct booking and reservation management.", "/services/custom-software-development"], ["Guest AI assistant", "Answers queries and takes requests on WhatsApp.", "/products/ai-agents"], ["Operations app", "Housekeeping and maintenance tasks.", "/services/mobile-app-development"], ["Hospitality HRMS", "Rosters, attendance and payroll.", "/products/hrms"]],
    features: ["Direct booking engine", "Guest messaging", "Housekeeping status", "Kitchen inventory", "Staff rostering", "Feedback collection"],
    useCases: [["Boutique hotel", "Direct bookings and guest messaging."], ["Restaurant group", "Inventory and staff across outlets."], ["Tour operator", "Bookings, itineraries and customer updates."]],
    benefits: ["More direct bookings", "Faster guest response", "Real-time room status", "Controlled costs"],
    workflow: ["Guest books", "Confirmation sent", "Check-in", "Requests handled", "Room cleaned & updated", "Feedback collected"],
    relatedServices: ["custom-software-development", "ai-development", "mobile-app-development"], relatedProducts: ["ai-agents", "hrms", "inventory-management"],
  }),
  build({
    slug: "finance", name: "Finance", icon: "landmark", keyword: "Financial Services Software",
    headline: "Secure Software for Lending, Advisory and Financial Services",
    intro: "Financial services firms need secure customer onboarding, document processing, loan or case workflows and compliance-ready audit trails.",
    answer: "Financial services businesses typically need customer onboarding with document collection, application or case workflows, document verification, customer communication, reporting and strong audit trails. Automation and AI document processing reduce turnaround times while role-based access and logging support compliance requirements.",
    challenges: [["Document-heavy onboarding", "Manual collection and verification."], ["Case tracking", "Applications stuck between teams."], ["Audit requirements", "Need for complete activity trails."], ["Customer updates", "Status queries handled by phone."]],
    solutions: [["Onboarding portal", "Digital applications and document upload.", "/services/web-development"], ["Document intelligence", "AI extraction and validation of documents.", "/services/ai-development"], ["Case workflow", "Stages, approvals and SLAs.", "/products/business-automation"], ["Customer CRM", "Relationship and follow-up management.", "/products/crm"]],
    features: ["Digital onboarding", "Document upload & extraction", "Approval workflows", "Audit logs", "Customer status portal", "Reports"],
    useCases: [["Lending business", "Application to disbursal workflow."], ["Advisory firm", "Client onboarding and document management."], ["Insurance distributor", "Lead to policy tracking."]],
    benefits: ["Faster turnaround", "Fewer data entry errors", "Audit-ready records", "Better customer transparency"],
    workflow: ["Application submitted", "Documents extracted by AI", "Verification", "Approval workflow", "Customer notified", "Records archived"],
    relatedServices: ["ai-development", "business-automation", "custom-software-development"], relatedProducts: ["business-automation", "ai-agents", "crm"],
  }),
  build({
    slug: "logistics", name: "Logistics", icon: "truck", keyword: "Logistics Software Development",
    headline: "Track Every Shipment, Vehicle and Driver",
    intro: "Logistics operators coordinate orders, fleets, drivers, warehouses and customers in real time. We build dispatch, tracking and warehouse systems for them.",
    answer: "Logistics businesses typically need order and shipment management, dispatch planning, driver apps with proof of delivery, vehicle tracking, warehouse inventory, driver attendance and customer tracking portals. Connecting these systems reduces calls, improves on-time delivery and gives accurate billing data.",
    challenges: [["Shipment visibility", "Customers calling for status."], ["Proof of delivery", "Paper PODs delay billing."], ["Driver management", "Attendance and trip allowances."], ["Warehouse accuracy", "Stock mismatches."]],
    solutions: [["Dispatch & tracking", "Orders, trips and live status.", "/services/custom-software-development"], ["Driver app", "Trips, navigation and digital POD.", "/services/mobile-app-development"], ["Warehouse inventory", "Inbound, storage and outbound.", "/products/inventory-management"], ["Driver HRMS", "Attendance, trips and payroll.", "/products/hrms"]],
    features: ["Order management", "Trip planning", "Driver mobile app", "Digital proof of delivery", "Customer tracking link", "Warehouse module"],
    useCases: [["Transport company", "Trip management and driver app."], ["3PL warehouse", "Client-wise inventory and dispatch."], ["Distribution business", "Route planning and delivery tracking."]],
    benefits: ["Fewer status calls", "Faster billing", "Accountable drivers", "Accurate inventory"],
    workflow: ["Order booked", "Trip planned", "Driver assigned", "Live updates", "Digital POD", "Invoice generated"],
    relatedServices: ["mobile-app-development", "custom-software-development", "cloud-devops"], relatedProducts: ["inventory-management", "hrms", "business-automation"],
  }),
  build({
    slug: "automotive", name: "Automotive", icon: "car", keyword: "Automotive Dealer Software",
    headline: "Software for Dealers, Workshops and Automotive Distributors",
    intro: "Automotive dealers and service centres manage leads, test drives, bookings, service jobs, spare parts and customer follow-ups. We build dealer management systems that connect them.",
    answer: "Automotive dealers and workshops typically need lead and test drive management, vehicle and spare parts inventory, service job cards, customer reminders for service due dates, and staff management. A dealer management system connects sales and service so every customer interaction is tracked.",
    challenges: [["Lead leakage", "Walk-in and online enquiries not followed up."], ["Service reminders", "Due dates tracked manually."], ["Spare parts", "Inventory across branches."], ["Job card tracking", "Workshop status unclear."]],
    solutions: [["Dealer CRM", "Leads, test drives and bookings.", "/products/crm"], ["Service management", "Job cards, estimates and reminders.", "/services/custom-software-development"], ["Parts inventory", "Multi-branch spare parts.", "/products/inventory-management"], ["Customer app", "Service booking and status.", "/services/mobile-app-development"]],
    features: ["Lead & test drive tracking", "Vehicle inventory", "Job cards", "Spare parts", "Service reminders", "Customer app"],
    useCases: [["Two-wheeler dealer", "Sales and service in one system."], ["Multi-brand workshop", "Job cards and parts."], ["Parts distributor", "Dealer ordering and inventory."]],
    benefits: ["More conversions", "Repeat service visits", "Accurate parts stock", "Transparent workshop status"],
    workflow: ["Enquiry captured", "Test drive booked", "Vehicle sold", "Service reminder sent", "Job card opened", "Invoice & feedback"],
    relatedServices: ["crm-development", "erp-development", "mobile-app-development"], relatedProducts: ["crm", "inventory-management", "lead-management"],
  }),
  build({
    slug: "professional-services", name: "Professional Services", icon: "scale", keyword: "Professional Services Software",
    headline: "Run Your Practice on Systems, Not Spreadsheets",
    intro: "Consultancies, agencies, CA and legal firms need client management, project and time tracking, documents and billing working together.",
    answer: "Professional services firms typically need client relationship management, engagement or project tracking, time and work logs, document management, invoicing and team utilisation reporting. Integrated systems improve billing accuracy and give partners visibility into workload and profitability.",
    challenges: [["Scattered client data", "Emails, files and notes in different places."], ["Time tracking", "Unbilled hours and inaccurate invoices."], ["Compliance deadlines", "Tracked in calendars and memory."], ["Document handling", "Client documents exchanged by email."]],
    solutions: [["Practice CRM", "Clients, engagements and follow-ups.", "/products/crm"], ["Work & time tracking", "Tasks, logs and utilisation.", "/products/hrms"], ["Client portal", "Secure document exchange.", "/services/web-development"], ["AI document assistant", "Summaries and data extraction.", "/services/ai-development"]],
    features: ["Client management", "Engagement tracking", "Time logs", "Deadline reminders", "Client portal", "Invoicing"],
    useCases: [["CA firm", "Compliance calendar and client portal."], ["Agency", "Projects, time and billing."], ["Consultancy", "Engagements and utilisation."]],
    benefits: ["Accurate billing", "No missed deadlines", "Secure documents", "Clear utilisation"],
    workflow: ["Client onboarded", "Engagement created", "Tasks assigned", "Time logged", "Documents exchanged", "Invoice raised"],
    relatedServices: ["crm-development", "business-automation", "ai-development"], relatedProducts: ["crm", "business-automation", "hrms"],
  }),
  build({
    slug: "startups", name: "Startups", icon: "rocket", keyword: "Software Development for Startups",
    headline: "Build Your MVP Right the First Time",
    intro: "Startups need to validate fast without building something that must be thrown away. We build MVPs and SaaS products with architecture that can grow.",
    answer: "Startups typically need a focused MVP that validates the core value proposition, with authentication, the primary workflow, payments or subscriptions, analytics and an admin panel. Building on a scalable architecture from the start avoids costly rewrites once the product finds traction.",
    challenges: [["Limited runway", "Every week and rupee counts."], ["Scope creep", "MVPs that try to do everything."], ["Scalability", "Prototypes that can't handle growth."], ["No tech team", "Founders without in-house engineering."]],
    solutions: [["MVP development", "Focused first version in weeks.", "/services/saas-development"], ["SaaS architecture", "Multi-tenant, billing-ready foundations.", "/services/saas-development"], ["AI features", "Differentiate with practical AI.", "/services/ai-development"], ["Technical consulting", "Architecture and roadmap guidance.", "/services/it-consulting"]],
    features: ["MVP scoping workshop", "Authentication & roles", "Subscription billing", "Product analytics", "Admin console", "CI/CD"],
    useCases: [["B2B SaaS", "Multi-tenant product with billing."], ["Marketplace", "Buyers, sellers and transactions."], ["AI-first product", "LLM-powered core workflow."]],
    benefits: ["Faster time to market", "Architecture that scales", "Clear scope and cost", "Technical partnership"],
    workflow: ["Idea workshop", "MVP scope", "Design prototype", "Build sprints", "Launch", "Iterate on feedback"],
    relatedServices: ["saas-development", "ai-development", "it-consulting"], relatedProducts: ["custom-business-software", "ai-agents"],
  }),
  build({
    slug: "smes", name: "SMEs", icon: "trending", keyword: "Business Software for SMEs",
    headline: "Enterprise-Grade Systems at SME Scale",
    intro: "Small and medium businesses often run on spreadsheets and messaging apps long after they've outgrown them. We help SMEs move to connected systems in affordable phases.",
    answer: "Small and medium enterprises typically need a CRM for sales follow-ups, inventory and billing, HRMS for attendance and payroll, and simple automation for approvals and notifications. Implementing these in phases, starting with the biggest bottleneck, lets SMEs digitise without large upfront investment.",
    challenges: [["Spreadsheet overload", "Critical data in many files."], ["Owner dependency", "Every decision needs the owner."], ["Budget constraints", "Need clear ROI per phase."], ["Adoption", "Staff resistant to complex software."]],
    solutions: [["Phased digital transformation", "Start with the highest-impact process.", "/services/digital-transformation"], ["SME CRM", "Leads and follow-ups.", "/products/crm"], ["HRMS", "Attendance and payroll.", "/products/hrms"], ["ERP essentials", "Inventory, billing and purchases.", "/products/erp"]],
    features: ["Phased rollout", "Simple, mobile-friendly UI", "Training & support", "Affordable modules", "Owner dashboard"],
    useCases: [["Trading business", "Inventory, billing and dealer CRM."], ["Service business", "Jobs, staff and invoicing."], ["Small manufacturer", "Orders, stock and attendance."]],
    benefits: ["Less owner dependency", "Clear ROI per phase", "Real-time business view", "Scalable foundation"],
    workflow: ["Identify bottleneck", "Digitise first process", "Train team", "Measure results", "Add next module", "Connect everything"],
    relatedServices: ["digital-transformation", "business-automation", "custom-software-development"], relatedProducts: ["crm", "hrms", "erp"],
  }),
  build({
    slug: "enterprise", name: "Enterprise", icon: "building", keyword: "Enterprise Software Development",
    headline: "Modernise and Extend Enterprise Systems",
    intro: "Enterprises need custom applications, integrations and AI capabilities that work alongside existing core systems, with security and governance built in.",
    answer: "Enterprises typically need custom applications for processes that core systems don't cover, integrations between ERP, CRM and HR systems, legacy modernisation, AI and automation initiatives, and strong security, access control and audit capabilities. Delivery must fit enterprise governance and IT standards.",
    challenges: [["Legacy systems", "Critical processes on ageing technology."], ["Integration gaps", "Systems that don't share data."], ["Governance", "Security, audit and compliance requirements."], ["AI adoption", "Pilots that don't reach production."]],
    solutions: [["Custom enterprise apps", "Department and process-specific systems.", "/services/custom-software-development"], ["Integration layer", "APIs and workflows across systems.", "/products/business-automation"], ["Legacy modernisation", "Re-platform and migrate safely.", "/services/cloud-devops"], ["Enterprise AI", "Governed RAG and agent deployments.", "/services/ai-development"]],
    features: ["SSO & role-based access", "Audit logging", "API integrations", "Scalable cloud architecture", "Documentation & handover", "SLA-based support"],
    useCases: [["Department platform", "Custom workflow for a business unit."], ["Integration hub", "Connecting ERP, CRM and HR."], ["Knowledge assistant", "Enterprise RAG over policies and documents."]],
    benefits: ["Faster modernisation", "Connected data", "Governed AI", "Reduced operational risk"],
    workflow: ["Assessment", "Architecture & security review", "Pilot", "Phased rollout", "Integration", "Support & SLA"],
    relatedServices: ["custom-software-development", "ai-development", "cloud-devops"], relatedProducts: ["custom-business-software", "ai-agents", "business-automation"],
  }),
];

export const getIndustry = (slug: string) => industries.find((i) => i.slug === slug);
export const featuredIndustrySlugs = ["healthcare", "education", "agriculture", "retail", "manufacturing", "enterprise"];
