import type { Product } from "./types";

/**
 * Product catalogue. `status` controls the badge:
 *  - "available": a packaged FairBazaar product.
 *  - "custom-deployment": a FairBazaar platform configured and deployed per client.
 * Update statuses as products move to general availability.
 */
export const products: Product[] = [
  {
    slug: "hrms",
    name: "FairBazaar HRMS",
    shortName: "HRMS",
    icon: "briefcase",
    category: "Workforce",
    status: "available",
    seoTitle: "FairBazaar HRMS | HRMS, Attendance & Payroll Software",
    metaDescription:
      "FairBazaar HRMS: employee management, location-based attendance, leave, payroll, expenses, invoices, performance, documents and HR analytics in one platform with manager and admin dashboards.",
    tagline: "One platform. Complete workforce management.",
    headline: "Your Entire Workforce. One Intelligent Platform.",
    intro:
      "FairBazaar HRMS brings attendance, leave, payroll, expenses and performance into one connected platform — with location-verified check-ins for field teams and real-time dashboards for managers and HR.",
    answer: {
      question: "What does FairBazaar HRMS do?",
      text:
        "FairBazaar HRMS is a human resource management platform that manages employee records, attendance including location-based check-in, leave and holidays, payroll, expenses and invoices, performance and work progress, employee documents and HR analytics, with separate dashboards and permissions for employees, managers and administrators.",
    },
    highlights: ["Location-verified attendance", "Attendance-linked payroll", "Leave & expense approvals", "Manager & admin dashboards", "Role-based access", "HR analytics"],
    modules: [
      { title: "Employee Management", text: "Profiles, departments, reporting lines and lifecycle events.", icon: "users" },
      { title: "Attendance", text: "Shift-aware attendance with regularisation requests.", icon: "calendar" },
      { title: "Location-Based Attendance", text: "Geo-fenced mobile check-in for field and multi-site teams.", icon: "map" },
      { title: "Payroll", text: "Attendance-linked salary calculation and payslips.", icon: "wallet" },
      { title: "Leave Management", text: "Leave types, balances, policies and approval chains.", icon: "clipboard" },
      { title: "Holiday Management", text: "Location-wise holiday calendars.", icon: "calendar" },
      { title: "Expense Management", text: "Claims with receipts, limits and approvals.", icon: "receipt" },
      { title: "Invoice Management", text: "Contractor and vendor invoices tracked with approvals.", icon: "file" },
      { title: "Performance Management", text: "Goals, reviews and feedback cycles.", icon: "target" },
      { title: "Work Progress", text: "Daily work logs and task progress tracking.", icon: "trending" },
      { title: "Employee Documents", text: "Secure storage for contracts, IDs and letters.", icon: "lock" },
      { title: "Reports", text: "Attendance, payroll, leave and expense reports.", icon: "chart" },
      { title: "HR Analytics", text: "Headcount, attrition, attendance and cost trends.", icon: "gauge" },
      { title: "Role-Based Access", text: "Granular permissions by role and department.", icon: "shield" },
      { title: "Manager Dashboard", text: "Team attendance, approvals and progress at a glance.", icon: "layers" },
      { title: "Admin Dashboard", text: "Organisation-wide control, settings and audit.", icon: "settings" },
    ],
    workflow: [
      "Employee checks in from mobile",
      "Location verified against geo-fence",
      "Attendance recorded in real time",
      "Manager dashboard updates",
      "Leave request submitted and approved",
      "Expense claim submitted with receipt",
      "Payroll calculated from attendance",
      "HR analytics updated",
    ],
    roles: [
      { role: "Employees", text: "Check in, apply for leave, submit expenses, view payslips and documents." },
      { role: "Managers", text: "Approve requests, monitor team attendance and track work progress." },
      { role: "HR & Admin", text: "Configure policies, run payroll, manage records and analyse workforce data." },
    ],
    deployment: ["Cloud-hosted SaaS", "Web and mobile access", "Custom configuration for policies", "Data import from spreadsheets"],
    mockup: "hrms",
    faqs: [
      { q: "Does FairBazaar HRMS support location-based attendance?", a: "Yes. Employees check in from the mobile app and the location is verified against configured geo-fences for each office or site." },
      { q: "Is payroll connected to attendance?", a: "Yes. Payroll uses attendance, leave and configured pay components to calculate salaries and generate payslips." },
      { q: "Can managers approve leave and expenses?", a: "Yes. Approval chains are configurable, and managers can approve from web or mobile." },
      { q: "Can FairBazaar HRMS be customised?", a: "Yes. Policies, roles and workflows are configurable, and custom modules can be developed for specific requirements." },
      { q: "How do we request an HRMS demo?", a: "Use the Request an HRMS Demo button and our team will schedule a walkthrough tailored to your organisation." },
    ],
    relatedServices: ["hrms-development", "mobile-app-development", "business-automation"],
    relatedIndustries: ["manufacturing", "healthcare", "education", "logistics"],
    relatedPosts: ["what-is-hrms-software", "location-based-attendance-guide"],
  },
  {
    slug: "crm",
    name: "FairBazaar CRM",
    shortName: "CRM",
    icon: "users",
    category: "Sales",
    status: "custom-deployment",
    seoTitle: "FairBazaar CRM | Sales Pipeline & Customer Management Platform",
    metaDescription:
      "FairBazaar CRM manages leads, customers, deals, follow-ups, sales pipeline, communication and reports — configurable for your sales process.",
    tagline: "Every lead, deal and follow-up — in one place.",
    headline: "Close More Deals With a CRM That Fits Your Process",
    intro: "A configurable CRM platform for teams that sell through enquiries, dealers, field sales or inside sales — deployed and adapted to your pipeline.",
    answer: {
      question: "What is FairBazaar CRM?",
      text:
        "FairBazaar CRM is a customer relationship management platform for managing leads, customers, deals and follow-ups through a configurable sales pipeline. It centralises communication history, automates reminders and assignment, and provides sales reports, and it is deployed and adapted to each organisation's sales process.",
    },
    highlights: ["Custom pipeline stages", "Automatic lead assignment", "Follow-up reminders", "WhatsApp & email logging", "Sales dashboards"],
    modules: [
      { title: "Leads", text: "Capture from web, ads, WhatsApp and imports.", icon: "target" },
      { title: "Customers", text: "Unified customer profiles and history.", icon: "users" },
      { title: "Deals", text: "Value, stage, probability and owner tracking.", icon: "wallet" },
      { title: "Follow-ups", text: "Tasks, reminders and escalations.", icon: "bell" },
      { title: "Sales Pipeline", text: "Kanban pipeline with custom stages.", icon: "layers" },
      { title: "Communication", text: "Calls, emails and messages linked to records.", icon: "message" },
      { title: "Reports", text: "Conversion, source and team performance.", icon: "chart" },
    ],
    workflow: ["Lead captured from website", "Auto-assigned to salesperson", "Follow-up scheduled", "Deal moves through pipeline", "Quotation sent", "Deal won and handed to operations"],
    roles: [
      { role: "Sales executives", text: "Manage leads, log calls and follow up on time." },
      { role: "Sales managers", text: "Monitor pipeline, reassign leads and forecast." },
      { role: "Leadership", text: "Track revenue pipeline and channel performance." },
    ],
    deployment: ["Cloud deployment", "Configured pipeline & fields", "Integrations with website and messaging"],
    mockup: "crm",
    faqs: [
      { q: "Can FairBazaar CRM be customised?", a: "Yes. Pipeline stages, fields, roles and automations are configured for your process, and custom modules can be added." },
      { q: "Can it capture leads from our website automatically?", a: "Yes. Website forms and landing pages can post leads directly into the CRM with source tracking." },
    ],
    relatedServices: ["crm-development", "business-automation", "ai-development"],
    relatedIndustries: ["real-estate", "automotive", "education", "professional-services"],
    relatedPosts: ["custom-crm-vs-ready-made-crm"],
  },
  {
    slug: "erp",
    name: "FairBazaar ERP",
    shortName: "ERP",
    icon: "boxes",
    category: "Operations",
    status: "custom-deployment",
    seoTitle: "FairBazaar ERP | Inventory, Purchasing, Sales & Finance Platform",
    metaDescription:
      "FairBazaar ERP connects inventory, purchasing, sales, finance, operations and employees in one configurable business platform with real-time reporting.",
    tagline: "Operations, inventory and finance — connected.",
    headline: "Run Your Operations From One Source of Truth",
    intro: "A modular ERP platform that connects inventory, purchasing, sales, finance and operations — configured for your business and extended where you need it.",
    answer: {
      question: "What is FairBazaar ERP?",
      text:
        "FairBazaar ERP is a modular enterprise resource planning platform that connects inventory, purchasing, sales, finance, operations and employee data in one system. Businesses deploy the modules they need, configure them to their processes, and get real-time reports across departments instead of reconciling separate spreadsheets.",
    },
    highlights: ["Multi-location inventory", "Purchase-to-pay", "Order-to-cash", "Approval workflows", "Real-time reports"],
    modules: [
      { title: "Inventory", text: "Stock, batches, transfers and reorder alerts.", icon: "package" },
      { title: "Purchasing", text: "Requisitions, POs, vendors and receipts.", icon: "receipt" },
      { title: "Sales", text: "Quotes, orders, invoices and dispatch.", icon: "store" },
      { title: "Finance", text: "Receivables, payables and expenses.", icon: "wallet" },
      { title: "Operations", text: "Work orders, jobs and quality.", icon: "settings" },
      { title: "Employees", text: "Linked with FairBazaar HRMS.", icon: "users" },
      { title: "Reports", text: "Cross-module management dashboards.", icon: "chart" },
    ],
    workflow: ["Sales order created", "Stock reserved", "Purchase triggered at reorder level", "Goods received", "Invoice generated", "Payment reconciled", "Reports updated"],
    roles: [
      { role: "Operations", text: "Manage stock, orders and fulfilment." },
      { role: "Finance", text: "Track receivables, payables and margins." },
      { role: "Management", text: "See the whole business in real time." },
    ],
    deployment: ["Modular rollout", "Cloud deployment", "Data migration", "Accounting integrations"],
    mockup: "erp",
    faqs: [
      { q: "Can we start with only a few ERP modules?", a: "Yes. Most organisations start with inventory and sales and add purchasing, finance and operations in later phases." },
      { q: "Is FairBazaar ERP suitable for manufacturers?", a: "Yes. Production, bill-of-materials and job tracking modules can be configured for manufacturing workflows." },
    ],
    relatedServices: ["erp-development", "business-automation", "digital-transformation"],
    relatedIndustries: ["manufacturing", "retail", "agriculture", "logistics"],
    relatedPosts: ["custom-erp-vs-ready-made-erp"],
  },
  {
    slug: "lead-management",
    name: "FairBazaar Lead Management",
    shortName: "Lead Management",
    icon: "target",
    category: "Sales",
    status: "custom-deployment",
    seoTitle: "Lead Management Software | Capture, Assign & Convert | FairBazaar",
    metaDescription:
      "Lead management software to capture leads from every channel, assign automatically, track follow-ups and measure source-wise conversion.",
    tagline: "Capture every enquiry. Convert more of them.",
    headline: "Never Lose Another Lead",
    intro: "Capture leads from websites, ads, WhatsApp and walk-ins, route them to the right person instantly and track every follow-up until conversion.",
    answer: {
      question: "What is lead management software?",
      text:
        "Lead management software captures enquiries from every channel, assigns them to salespeople based on rules, schedules follow-ups and tracks each lead until it converts or closes. It helps businesses respond faster, stop leads falling through the cracks and understand which marketing sources produce customers.",
    },
    highlights: ["Multi-channel capture", "Rule-based assignment", "Follow-up tracking", "Source & UTM attribution", "Conversion analytics"],
    modules: [
      { title: "Capture", text: "Web forms, landing pages, ads, WhatsApp, imports.", icon: "link" },
      { title: "Assignment", text: "Round-robin, territory and skill-based routing.", icon: "workflow" },
      { title: "Follow-ups", text: "Reminders and overdue alerts.", icon: "bell" },
      { title: "Attribution", text: "UTM and source tracking per lead.", icon: "target" },
      { title: "Analytics", text: "Source-wise and team-wise conversion.", icon: "chart" },
    ],
    workflow: ["Enquiry received", "Source and UTM captured", "Lead auto-assigned", "Salesperson notified", "Follow-up logged", "Converted to customer"],
    roles: [
      { role: "Marketing", text: "See which campaigns produce real customers." },
      { role: "Sales", text: "Get leads instantly with full context." },
    ],
    deployment: ["Cloud deployment", "Website & ad integrations", "Upgradeable to full CRM"],
    mockup: "leads",
    faqs: [{ q: "What is the difference between lead management and CRM?", a: "Lead management focuses on capturing and converting enquiries; a CRM also manages ongoing customer relationships, deals and post-sale communication. FairBazaar Lead Management can be upgraded to FairBazaar CRM." }],
    relatedServices: ["crm-development", "web-development", "business-automation"],
    relatedIndustries: ["real-estate", "education", "automotive"],
    relatedPosts: ["custom-crm-vs-ready-made-crm"],
  },
  {
    slug: "inventory-management",
    name: "FairBazaar Inventory",
    shortName: "Inventory",
    icon: "package",
    category: "Operations",
    status: "custom-deployment",
    seoTitle: "Inventory Management Software | Multi-location Stock | FairBazaar",
    metaDescription:
      "Inventory management software for multi-location stock, batches, transfers, reorder alerts, purchase and sales integration and stock reports.",
    tagline: "Know exactly what you have, and where.",
    headline: "Real-Time Stock Across Every Location",
    intro: "Track stock across warehouses, stores and vehicles, with batch tracking, transfers and reorder alerts connected to purchasing and sales.",
    answer: {
      question: "What does inventory management software do?",
      text:
        "Inventory management software tracks stock quantities, locations and movements in real time. It records purchases, sales, transfers and adjustments, alerts teams when items reach reorder levels, tracks batches and expiry, and produces valuation and movement reports so businesses avoid stockouts and excess inventory.",
    },
    highlights: ["Multi-location stock", "Batch & expiry tracking", "Reorder alerts", "Barcode-ready", "Stock valuation"],
    modules: [
      { title: "Stock Ledger", text: "Every movement recorded and traceable.", icon: "database" },
      { title: "Locations", text: "Warehouses, stores and bins.", icon: "map" },
      { title: "Transfers", text: "Inter-location transfers with approvals.", icon: "truck" },
      { title: "Reorder", text: "Min/max levels and purchase suggestions.", icon: "bell" },
      { title: "Reports", text: "Valuation, ageing and movement.", icon: "chart" },
    ],
    workflow: ["Goods received", "Stock updated by location", "Sale deducts stock", "Reorder level reached", "Purchase suggested", "Transfer between locations"],
    roles: [{ role: "Store & warehouse teams", text: "Receive, pick, transfer and count stock." }, { role: "Management", text: "Monitor stock value and movement." }],
    deployment: ["Standalone or as an ERP module", "Web and mobile scanning"],
    mockup: "inventory",
    faqs: [{ q: "Can inventory connect with our billing or ERP?", a: "Yes. It works as a module of FairBazaar ERP or integrates with existing billing systems." }],
    relatedServices: ["erp-development", "custom-software-development"],
    relatedIndustries: ["retail", "manufacturing", "agriculture", "logistics"],
    relatedPosts: ["custom-erp-vs-ready-made-erp"],
  },
  {
    slug: "business-automation",
    name: "FairBazaar Automation",
    shortName: "Automation",
    icon: "workflow",
    category: "Automation",
    status: "custom-deployment",
    seoTitle: "Business Automation Platform | Workflows & Approvals | FairBazaar",
    metaDescription:
      "FairBazaar Automation: workflows, approvals, notifications, integrations and analytics that connect your business systems and remove repetitive work.",
    tagline: "Workflows that run themselves.",
    headline: "Connect Your Systems. Automate the Routine.",
    intro: "A workflow and integration layer that connects CRM, ERP, HRMS and external tools — triggering approvals, notifications and data sync automatically.",
    answer: {
      question: "What is a business automation platform?",
      text:
        "A business automation platform connects an organisation's software systems and runs rule-based workflows between them: routing approvals, sending notifications, syncing data and generating documents when events happen. It removes repetitive manual steps and gives teams visibility into where each process stands.",
    },
    highlights: ["Visual workflows", "Approval chains", "Multi-channel notifications", "API integrations", "Process analytics"],
    modules: [
      { title: "Workflows", text: "Triggers, conditions and actions.", icon: "workflow" },
      { title: "Notifications", text: "Email, SMS, WhatsApp and in-app.", icon: "bell" },
      { title: "Approvals", text: "Multi-level with SLAs.", icon: "clipboard" },
      { title: "Integrations", text: "REST APIs and webhooks.", icon: "link" },
      { title: "Analytics", text: "Process time and bottlenecks.", icon: "chart" },
    ],
    workflow: ["Event occurs in a system", "Workflow triggered", "Conditions evaluated", "Approval requested", "Systems updated", "Stakeholders notified"],
    roles: [{ role: "Operations leaders", text: "Standardise and monitor processes." }, { role: "Teams", text: "Spend less time on routine updates." }],
    deployment: ["Cloud deployment", "Connectors configured per client"],
    mockup: "automation",
    faqs: [{ q: "Does automation work with non-FairBazaar software?", a: "Yes. Any system with an API or webhook support can be connected." }],
    relatedServices: ["business-automation", "ai-development"],
    relatedIndustries: ["smes", "finance", "logistics"],
    relatedPosts: ["business-process-automation-guide", "ai-business-automation"],
  },
  {
    slug: "ai-agents",
    name: "FairBazaar AI Agents",
    shortName: "AI Agents",
    icon: "bot",
    category: "AI",
    status: "custom-deployment",
    seoTitle: "AI Agents for Business | Sales, Support & Operations | FairBazaar",
    metaDescription:
      "FairBazaar AI Agents answer customers, qualify leads, process documents and update business systems — grounded in your data and connected to your CRM, ERP and HRMS.",
    tagline: "AI that takes action inside your business.",
    headline: "AI Agents That Understand Your Business",
    intro: "AI agents grounded in your documents and connected to your systems — answering customers, qualifying leads, processing documents and completing tasks with the right approvals.",
    answer: {
      question: "What is an AI agent for business?",
      text:
        "An AI agent for business is software powered by a large language model that can understand requests, retrieve information from company data and take actions in business systems, such as creating CRM records, answering support questions or processing documents. Well-designed agents operate within defined permissions and escalate to humans when needed.",
    },
    highlights: ["Grounded in your data", "Tool & API actions", "Web & WhatsApp channels", "Human-in-the-loop", "Conversation analytics"],
    modules: [
      { title: "Support Agent", text: "Answers from your knowledge base with citations.", icon: "message" },
      { title: "Sales Agent", text: "Qualifies leads and books meetings.", icon: "target" },
      { title: "Document Agent", text: "Extracts and validates document data.", icon: "file" },
      { title: "Ops Agent", text: "Updates records and triggers workflows.", icon: "zap" },
      { title: "Analytics Agent", text: "Answers questions about your data in plain language.", icon: "chart" },
    ],
    workflow: ["Customer asks a question", "Agent retrieves relevant knowledge", "Answer drafted with sources", "Action taken in CRM", "Escalated to human if needed", "Analytics updated"],
    roles: [{ role: "Customers", text: "Instant, accurate answers." }, { role: "Teams", text: "Less repetitive work, better context." }],
    deployment: ["Cloud or private deployment", "Model-agnostic", "Access controls and logging"],
    mockup: "ai",
    faqs: [
      { q: "Can AI agents connect to our CRM or ERP?", a: "Yes. Agents are given controlled access to approved actions through APIs, with logging and optional human approval." },
      { q: "Which AI models do you use?", a: "We are model-agnostic and select commercial or open-source models based on accuracy, cost, latency and data requirements." },
    ],
    relatedServices: ["ai-development", "business-automation"],
    relatedIndustries: ["healthcare", "education", "retail", "finance"],
    relatedPosts: ["what-are-ai-agents", "rag-explained-for-business", "ai-business-automation"],
  },
  {
    slug: "custom-business-software",
    name: "Custom Business Software",
    shortName: "Custom Software",
    icon: "code",
    category: "Custom",
    status: "custom-deployment",
    seoTitle: "Custom Business Software Built on FairBazaar Platforms",
    metaDescription:
      "Custom business software built on proven FairBazaar platform components — authentication, roles, workflows, reporting — for faster, more reliable delivery.",
    tagline: "Your software, on a proven foundation.",
    headline: "Custom Software Without Starting From Zero",
    intro: "We build custom systems on reusable FairBazaar platform components — authentication, roles, audit logs, workflows, notifications and reporting — so your budget goes into what makes your business different.",
    answer: {
      question: "How is FairBazaar custom software delivered faster?",
      text:
        "FairBazaar builds custom business software on reusable platform components for authentication, roles and permissions, audit logging, workflows, notifications, file storage and reporting. Because these foundations are already built and tested, development effort focuses on the client's unique processes, which shortens delivery and improves reliability.",
    },
    highlights: ["Reusable secure foundation", "Role-based access", "Audit logging", "Workflow engine", "Reporting"],
    modules: [
      { title: "Identity & Roles", text: "Secure sign-in and permissions.", icon: "lock" },
      { title: "Workflow Engine", text: "Configurable processes.", icon: "workflow" },
      { title: "Audit Logs", text: "Who did what, when.", icon: "shield" },
      { title: "Reporting", text: "Dashboards and exports.", icon: "chart" },
      { title: "Integrations", text: "APIs and webhooks.", icon: "link" },
    ],
    workflow: ["Discovery", "Configure foundation", "Build unique modules", "Integrate", "Test", "Deploy"],
    roles: [{ role: "Business owners", text: "Software that fits, delivered sooner." }],
    deployment: ["Cloud or on-premise", "Full source ownership per agreement"],
    mockup: "custom",
    faqs: [{ q: "Do we own custom software built on your components?", a: "Ownership and licensing terms are defined in each agreement; typically the client owns all custom code and receives a licence to the platform components." }],
    relatedServices: ["custom-software-development", "it-consulting"],
    relatedIndustries: ["enterprise", "smes", "manufacturing"],
    relatedPosts: ["what-is-custom-software-development", "custom-software-development-cost"],
  },
];

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);
