import type { Service } from "./types";

const stdProcess = [
  { title: "Discover", text: "Workshops with your team to map goals, users, workflows and constraints." },
  { title: "Analyze", text: "Requirements, data flows and integration points documented and prioritised." },
  { title: "Design", text: "Architecture, UX flows and clickable prototypes validated before build." },
  { title: "Develop", text: "Agile sprints with demos every iteration and full source-code transparency." },
  { title: "Test", text: "Automated and manual QA, security review and user acceptance testing." },
  { title: "Deploy", text: "Cloud deployment with CI/CD, monitoring, backups and documentation." },
  { title: "Scale", text: "Ongoing support, performance tuning and feature roadmap." },
];

export const services: Service[] = [
  {
    slug: "custom-software-development",
    name: "Custom Software Development",
    navLabel: "Custom Software",
    icon: "code",
    pillar: true,
    seoTitle: "Custom Software Development Company in India | FairBazaar",
    metaDescription:
      "FairBazaar is a custom software development company in India building business platforms, enterprise software and workflow systems designed around how your organisation actually works.",
    headline: "Software Built Around Your Workflow",
    intro:
      "Off-the-shelf tools force your team to adapt to someone else's process. We design and build software that fits your operations, integrates with your existing systems and grows with your business.",
    answer: {
      question: "What is custom software development?",
      text:
        "Custom software development is the process of designing, building and maintaining software for one organisation's specific workflows, users and data. Unlike ready-made products, custom software is owned by the business, integrates with its existing systems and can be extended as requirements change, which makes it suited to processes that give a company its competitive edge.",
    },
    problems: [
      "Teams juggling spreadsheets, WhatsApp groups and disconnected tools",
      "Ready-made software that covers 60% of the need and blocks the rest",
      "Manual data entry repeated across departments",
      "No single view of operations for management decisions",
    ],
    offerings: [
      { title: "Enterprise Software", text: "Multi-department platforms with role-based access, audit trails and integrations." },
      { title: "Business Management Systems", text: "Operations, approvals, billing and reporting unified in one system." },
      { title: "Custom CRM & ERP", text: "Sales, inventory, purchasing and finance modules shaped to your process." },
      { title: "Inventory & Booking Systems", text: "Real-time stock, reservations, slots and resource scheduling." },
      { title: "Healthcare & Education Platforms", text: "Patient, appointment, student and course management systems." },
      { title: "Marketplace & Dealer Platforms", text: "Multi-vendor, dealer and distributor networks with order and commission flows." },
    ],
    process: stdProcess,
    outcomes: [
      "Processes that match how your team really works",
      "Full ownership of source code and data",
      "Fewer tools, fewer subscriptions, less manual work",
      "A platform that can be extended as the business grows",
    ],
    technologies: ["React", "Next.js", "TypeScript", "Python", "FastAPI", "Django", "Java / Spring Boot", "PostgreSQL", "Docker", "AWS"],
    faqs: [
      { q: "How long does custom software development take?", a: "A focused MVP typically takes 8–14 weeks. Larger multi-module platforms are delivered in phases, with the first usable release usually within 3–4 months. We give a timeline after the discovery workshop, once scope is clear." },
      { q: "How much does custom software cost?", a: "Cost depends on scope, number of user roles, integrations and compliance needs. We provide a fixed-scope estimate after discovery, and we can phase delivery so you invest in the highest-value modules first." },
      { q: "Will we own the source code?", a: "Yes. For custom development engagements, source code and data belong to you as defined in the project agreement." },
      { q: "Do you provide maintenance after launch?", a: "Yes. We offer support and maintenance plans covering bug fixes, security updates, monitoring and new feature development." },
      { q: "Can you work with our existing software?", a: "Yes. We regularly integrate with accounting tools, payment gateways, ERPs, CRMs and legacy databases through APIs or data connectors." },
    ],
    relatedProducts: ["custom-business-software", "erp", "crm"],
    relatedIndustries: ["manufacturing", "healthcare", "education", "retail"],
    relatedPosts: ["what-is-custom-software-development", "custom-software-vs-saas", "custom-software-development-cost", "how-to-choose-a-software-development-company"],
    keywords: ["custom software development company", "custom software development India", "enterprise software development", "custom business software"],
  },
  {
    slug: "ai-development",
    name: "AI Development",
    navLabel: "AI Development",
    icon: "brain",
    pillar: true,
    seoTitle: "AI Development Company | AI Agents, RAG & LLM Apps | FairBazaar",
    metaDescription:
      "FairBazaar develops AI agents, RAG systems, LLM applications and intelligent automation that understand your documents, customers and workflows. Build practical AI for your business.",
    headline: "AI That Works With Your Business",
    intro:
      "We build AI systems that understand your documents, customer requests and operational processes — and connect them to the CRM, ERP and HRMS tools your team already uses.",
    answer: {
      question: "What does an AI development company do?",
      text:
        "An AI development company designs and builds software that uses machine learning and large language models to perform business tasks. This includes AI agents that take actions, retrieval-augmented generation (RAG) systems that answer from company documents, document intelligence, AI customer support and workflow automation integrated with existing business systems.",
    },
    problems: [
      "Knowledge trapped in PDFs, emails and shared drives",
      "Support and sales teams answering the same questions repeatedly",
      "Manual document review, data extraction and report preparation",
      "AI pilots that never connect to real business systems",
    ],
    offerings: [
      { title: "AI Agents", text: "Agents that plan, call tools and complete multi-step tasks across your systems with human approval where needed." },
      { title: "RAG Systems", text: "Accurate answers grounded in your documents, policies and knowledge bases, with source citations." },
      { title: "LLM Applications", text: "Chat, summarisation, drafting and classification features embedded into your products." },
      { title: "Document Intelligence", text: "Extract structured data from invoices, forms, contracts and scanned documents." },
      { title: "AI Customer Support & Sales Assistants", text: "24/7 assistants on web and WhatsApp that qualify leads and resolve queries." },
      { title: "AI Workflow Automation & Analytics", text: "AI-driven routing, approvals, forecasting and natural-language reporting." },
    ],
    process: [
      { title: "Use-case discovery", text: "Identify high-value, feasible AI opportunities and define success criteria." },
      { title: "Data readiness", text: "Assess documents, databases and access controls; design the retrieval layer." },
      { title: "Prototype", text: "A working prototype evaluated on your real data within weeks." },
      { title: "Evaluate", text: "Measure accuracy, hallucination rate, latency and cost against test sets." },
      { title: "Integrate", text: "Connect to CRM, ERP, HRMS, email, WhatsApp and internal APIs." },
      { title: "Guardrails", text: "Permissions, human-in-the-loop approvals, logging and data protection." },
      { title: "Operate", text: "Monitoring, prompt and model updates, and continuous improvement." },
    ],
    outcomes: [
      "Faster responses to customers and internal teams",
      "Less time spent on repetitive document and data work",
      "Knowledge that is searchable and answerable in plain language",
      "AI that acts inside your systems, not in a separate chat window",
    ],
    technologies: ["LLMs (OpenAI, Anthropic, open-source)", "LangChain", "LangGraph", "Vector databases", "Python", "FastAPI", "PostgreSQL + pgvector", "Supabase"],
    faqs: [
      { q: "Can FairBazaar build AI agents?", a: "Yes. We build AI agents that use tools and APIs to complete tasks such as updating CRM records, drafting responses, processing documents and triggering workflows, with human approval steps where required." },
      { q: "Can you integrate AI into our existing software?", a: "Yes. We add AI features to existing applications through APIs, embedded assistants and background automations without rebuilding your system." },
      { q: "Is our data used to train public AI models?", a: "We design solutions using provider settings and architectures that keep your business data out of public model training, and we can deploy with private or self-hosted models where required." },
      { q: "What is RAG and why does it matter?", a: "Retrieval-augmented generation lets an AI answer questions using your own documents as the source, which improves accuracy and allows answers to cite where the information came from." },
      { q: "How do you prevent AI from giving wrong answers?", a: "We ground responses in retrieved sources, evaluate against test question sets, restrict the AI to approved actions, and add human review for sensitive decisions." },
    ],
    relatedProducts: ["ai-agents", "business-automation", "crm"],
    relatedIndustries: ["healthcare", "education", "finance", "retail"],
    relatedPosts: ["ai-business-automation", "what-are-ai-agents", "rag-explained-for-business"],
    keywords: ["AI development company", "AI software development", "AI agent development", "AI automation services"],
  },
  {
    slug: "saas-development",
    name: "SaaS Product Development",
    navLabel: "SaaS Development",
    icon: "layers",
    pillar: true,
    seoTitle: "SaaS Development Company | SaaS Product Development | FairBazaar",
    metaDescription:
      "SaaS product development from MVP to scale: multi-tenant architecture, subscriptions and billing, onboarding, admin consoles and analytics — built by a team that runs its own SaaS products.",
    headline: "From SaaS Idea to Subscription Revenue",
    intro:
      "We build and operate our own SaaS products, so we design yours with the same concerns: multi-tenancy, billing, onboarding, security and the ability to ship features every week.",
    answer: {
      question: "What is SaaS product development?",
      text:
        "SaaS product development is building software delivered over the internet on a subscription basis, where many customers share one application while their data stays isolated. It covers multi-tenant architecture, user and organisation management, subscription billing, onboarding, admin tools, analytics, and the infrastructure to release updates continuously.",
    },
    problems: [
      "An idea validated with customers but no product team",
      "An MVP that can't handle multiple customers safely",
      "Billing, plans and trials built as an afterthought",
      "Slow release cycles that stall growth",
    ],
    offerings: [
      { title: "MVP Development", text: "A focused first version to validate with paying customers." },
      { title: "Multi-tenant Architecture", text: "Secure tenant isolation, roles and organisation management." },
      { title: "Subscriptions & Billing", text: "Plans, trials, usage limits, invoices and payment gateways." },
      { title: "Onboarding & Admin", text: "Self-serve sign-up, guided setup and internal admin consoles." },
      { title: "Product Analytics", text: "Activation, retention and feature-usage tracking." },
      { title: "AI Features", text: "Assistants, automation and insights built into the product." },
    ],
    process: stdProcess,
    outcomes: [
      "A production-ready SaaS foundation",
      "Faster time from idea to first paying customer",
      "Architecture ready for more tenants and features",
      "Continuous delivery of improvements",
    ],
    technologies: ["Next.js", "React", "TypeScript", "FastAPI", "PostgreSQL", "Supabase", "Stripe / Razorpay", "Docker", "AWS"],
    faqs: [
      { q: "Can FairBazaar build SaaS products?", a: "Yes. We build SaaS products end to end — from MVP scoping to multi-tenant architecture, billing and ongoing development — and we operate SaaS products of our own, including FairBazaar HRMS." },
      { q: "How long does it take to build a SaaS MVP?", a: "A focused SaaS MVP typically takes 10–16 weeks depending on the core workflow, integrations and billing requirements." },
      { q: "Who owns the SaaS product you build?", a: "For client SaaS engagements, the product, code and customer data belong to the client as defined in the agreement." },
    ],
    relatedProducts: ["hrms", "crm", "ai-agents"],
    relatedIndustries: ["startups", "enterprise", "education"],
    relatedPosts: ["custom-software-vs-saas", "what-is-custom-software-development"],
    keywords: ["SaaS development company", "SaaS product development", "SaaS MVP development India"],
  },
  {
    slug: "web-development",
    name: "Web Development",
    navLabel: "Web Development",
    icon: "globe",
    seoTitle: "Web Application Development Company | FairBazaar",
    metaDescription:
      "Corporate websites, SaaS websites, e-commerce, customer portals and web applications built for speed, SEO and conversion by FairBazaar.",
    headline: "Web Experiences Built to Perform",
    intro:
      "Your website and web applications are where customers form their first opinion and where your team does its daily work. We build them to load fast, rank well and convert.",
    answer: {
      question: "What is web application development?",
      text:
        "Web application development is the building of interactive software that runs in a browser, such as customer portals, admin dashboards, SaaS products and e-commerce platforms. Unlike a brochure website, a web application stores data, manages user accounts and supports business workflows, and it is accessible from any device without installation.",
    },
    problems: [
      "Slow websites that lose visitors before the page loads",
      "Sites that look good but generate few enquiries",
      "Customer requests handled over email instead of self-service portals",
      "Admin work done in spreadsheets because there is no dashboard",
    ],
    offerings: [
      { title: "Corporate & SaaS Websites", text: "Fast, SEO-ready marketing sites with CMS and conversion tracking." },
      { title: "E-commerce", text: "Catalogues, carts, payments, order management and integrations." },
      { title: "Web Applications", text: "Business apps with accounts, workflows, data and reporting." },
      { title: "Customer Portals", text: "Self-service for orders, tickets, documents and invoices." },
      { title: "Admin Dashboards", text: "Operational control panels with analytics and role-based access." },
      { title: "Landing Pages & SEO Websites", text: "Campaign pages and content architectures designed to rank and convert." },
    ],
    process: stdProcess,
    outcomes: [
      "Faster load times and better Core Web Vitals",
      "Higher search visibility through technical SEO",
      "More enquiries through clear journeys and CTAs",
      "Less manual admin through self-service portals",
    ],
    technologies: ["React", "Next.js", "TypeScript", "HTML/CSS", "JavaScript", "Python", "Django", "FastAPI", "PHP", "MySQL", "PostgreSQL", "Supabase"],
    faqs: [
      { q: "Do you build SEO-friendly websites?", a: "Yes. We build with server-side rendering, structured data, clean URLs, sitemaps and Core Web Vitals in mind, and structure content so search engines and AI answer systems understand it." },
      { q: "Can we update the website content ourselves?", a: "Yes. We connect a CMS so your team can publish pages and blog articles without changing code." },
      { q: "Do you build e-commerce websites?", a: "Yes, including catalogue management, payment gateway integration, order workflows and inventory sync." },
      { q: "Which technology do you use for websites?", a: "We choose the stack based on your needs; for most modern sites we use Next.js and React for performance and SEO, with PHP or Python backends where appropriate." },
    ],
    relatedProducts: ["lead-management", "crm"],
    relatedIndustries: ["retail", "real-estate", "education", "startups"],
    relatedPosts: ["website-vs-web-application", "how-to-choose-a-software-development-company"],
    keywords: ["web application development", "website development company", "Next.js development", "e-commerce development"],
  },
  {
    slug: "mobile-app-development",
    name: "Mobile App Development",
    navLabel: "Mobile Apps",
    icon: "smartphone",
    seoTitle: "Mobile App Development Company | Android, iOS, Flutter | FairBazaar",
    metaDescription:
      "Android, iOS and cross-platform mobile app development with React Native and Flutter — customer apps, employee apps, field workforce and marketplace apps by FairBazaar.",
    headline: "Mobile Apps Your Customers and Teams Actually Use",
    intro:
      "From field workforce apps with GPS attendance to customer ordering apps, we design and build mobile experiences that work reliably on real devices and real networks.",
    answer: {
      question: "Should I build a native or cross-platform mobile app?",
      text:
        "For most business apps, a cross-platform framework such as React Native or Flutter delivers Android and iOS apps from one codebase, reducing cost and time to market. Native development is preferable when an app depends heavily on advanced device features, complex graphics or platform-specific performance.",
    },
    problems: [
      "Field teams reporting work over phone calls and messages",
      "Customers expecting to order, book and track on mobile",
      "Separate Android and iOS budgets stretching timelines",
      "Apps that break on low-end devices or poor connectivity",
    ],
    offerings: [
      { title: "Android & iOS Apps", text: "Native-quality apps published to Google Play and the App Store." },
      { title: "Cross-platform Apps", text: "React Native and Flutter apps from a single codebase." },
      { title: "Employee & Field Workforce Apps", text: "GPS attendance, task lists, visit reports and offline sync." },
      { title: "Customer Apps", text: "Ordering, booking, loyalty, payments and notifications." },
      { title: "Marketplace Apps", text: "Buyer, seller and delivery apps with real-time updates." },
      { title: "Business Apps", text: "Mobile companions for your CRM, ERP and HRMS." },
    ],
    process: stdProcess,
    outcomes: [
      "One codebase for Android and iOS where it makes sense",
      "Offline-capable apps for field conditions",
      "Real-time data flowing into your back-office systems",
      "Store-ready releases with analytics and crash reporting",
    ],
    technologies: ["React Native", "Flutter", "Kotlin", "Swift", "Firebase", "Supabase", "FastAPI", "PostgreSQL"],
    faqs: [
      { q: "Do you develop mobile apps for both Android and iOS?", a: "Yes. We build native and cross-platform apps and handle publishing to Google Play and the Apple App Store." },
      { q: "Can the app work offline?", a: "Yes. Field and workforce apps can store data locally and sync when connectivity returns." },
      { q: "Can the mobile app connect to our existing system?", a: "Yes. We build secure APIs or integrate with your existing backend so data stays consistent across web and mobile." },
    ],
    relatedProducts: ["hrms", "crm", "lead-management"],
    relatedIndustries: ["agriculture", "logistics", "retail", "healthcare"],
    relatedPosts: ["native-vs-cross-platform-apps"],
    keywords: ["mobile app development company", "Flutter app development", "React Native development", "Android app development India"],
  },
  {
    slug: "crm-development",
    name: "CRM Development",
    navLabel: "CRM Development",
    icon: "users",
    pillar: true,
    seoTitle: "Custom CRM Development Company | CRM Software Development | FairBazaar",
    metaDescription:
      "Custom CRM software development for sales pipelines, lead management, follow-ups, customer communication and reporting — built around your sales process by FairBazaar.",
    headline: "A CRM Shaped Around How You Sell",
    intro:
      "Every sales process is different — dealer networks, B2B enquiries, walk-in customers, field sales. We build CRMs that match your pipeline stages, your team structure and your communication channels.",
    answer: {
      question: "What is custom CRM development?",
      text:
        "Custom CRM development is building a customer relationship management system around a company's own sales stages, lead sources, team structure and communication channels. It centralises leads, customers, deals and follow-ups, automates reminders and assignment, and produces reports that match how management measures the sales process.",
    },
    problems: [
      "Leads lost between WhatsApp, calls, email and spreadsheets",
      "No visibility into which salesperson is following up",
      "Generic CRMs with fields and stages that don't fit",
      "Per-user subscription costs growing with the team",
    ],
    offerings: [
      { title: "Lead & Pipeline Management", text: "Capture, assign, score and track leads through custom stages." },
      { title: "Customer 360", text: "Every interaction, order, document and ticket in one profile." },
      { title: "Follow-up Automation", text: "Reminders, sequences and escalations so no lead goes cold." },
      { title: "Communication", text: "WhatsApp, email, SMS and call logging integrated with records." },
      { title: "Sales Reports", text: "Conversion, source, team performance and forecast dashboards." },
      { title: "Dealer & Channel CRM", text: "Manage distributors, dealers and partner-sourced deals." },
    ],
    process: stdProcess,
    outcomes: [
      "Every lead captured and assigned automatically",
      "Clear visibility into pipeline and team activity",
      "Faster follow-ups through automation",
      "Reports that reflect your real sales process",
    ],
    technologies: ["Next.js", "React", "FastAPI", "Django", "PostgreSQL", "WhatsApp Business API", "Email/SMS gateways"],
    faqs: [
      { q: "Do you develop custom CRM software?", a: "Yes. We build custom CRMs and also offer the FairBazaar CRM platform, which can be configured and extended for your sales process." },
      { q: "Custom CRM or ready-made CRM — which is better?", a: "Ready-made CRMs suit standard sales processes. A custom or configurable CRM is better when your stages, dealer structure or integrations are specific, or when per-user pricing becomes expensive at scale." },
      { q: "Can the CRM integrate with WhatsApp and our website?", a: "Yes. Website forms, landing pages, WhatsApp and advertising lead sources can feed directly into the CRM." },
    ],
    relatedProducts: ["crm", "lead-management", "ai-agents"],
    relatedIndustries: ["real-estate", "automotive", "education", "professional-services"],
    relatedPosts: ["custom-crm-vs-ready-made-crm", "custom-software-vs-saas"],
    keywords: ["CRM software development", "custom CRM development", "CRM development company India"],
  },
  {
    slug: "erp-development",
    name: "ERP Development",
    navLabel: "ERP Development",
    icon: "boxes",
    pillar: true,
    seoTitle: "Custom ERP Software Development Company | FairBazaar",
    metaDescription:
      "Custom ERP development for inventory, purchasing, sales, finance, operations and reporting. FairBazaar builds ERP systems that fit your business instead of forcing you to fit the ERP.",
    headline: "One System for Your Entire Operation",
    intro:
      "We build ERP platforms that connect inventory, purchasing, sales, finance and operations — designed around your processes, with the modules you need and none you don't.",
    answer: {
      question: "What is custom ERP development?",
      text:
        "Custom ERP development is building an enterprise resource planning system tailored to a company's operations, connecting modules such as inventory, purchasing, sales, production, finance and HR in one database. It replaces disconnected tools with a single source of truth and adapts to industry-specific processes that generic ERPs handle poorly.",
    },
    problems: [
      "Stock, sales and accounts that never reconcile",
      "Generic ERP implementations that took months and still don't fit",
      "Manual purchase orders and approval chains",
      "Management reports assembled by hand every month",
    ],
    offerings: [
      { title: "Inventory & Warehouse", text: "Multi-location stock, batches, serials, transfers and reorder levels." },
      { title: "Purchasing", text: "Requisitions, POs, vendor management and goods receipt." },
      { title: "Sales & Billing", text: "Quotations, orders, invoicing, GST-ready documents and dispatch." },
      { title: "Finance", text: "Receivables, payables, expenses and accounting integrations." },
      { title: "Operations & Production", text: "Work orders, BOMs, job tracking and quality checks." },
      { title: "Reports & Analytics", text: "Real-time dashboards for management across every module." },
    ],
    process: stdProcess,
    outcomes: [
      "A single source of truth across departments",
      "Real-time stock and financial visibility",
      "Automated approvals and document generation",
      "An ERP that evolves with your operations",
    ],
    technologies: ["Next.js", "React", "Python", "Django", "Java / Spring Boot", "PostgreSQL", "Docker", "AWS"],
    faqs: [
      { q: "Do you develop ERP systems?", a: "Yes. We build custom ERP systems and offer the FairBazaar ERP platform as a configurable foundation for faster delivery." },
      { q: "Can the ERP be implemented in phases?", a: "Yes. We usually start with the modules that remove the most manual work, such as inventory and sales, and add finance, production or HR in later phases." },
      { q: "Can the ERP integrate with our accounting software?", a: "Yes. We integrate with accounting tools and other systems through APIs or scheduled data exchange." },
    ],
    relatedProducts: ["erp", "inventory-management", "business-automation"],
    relatedIndustries: ["manufacturing", "retail", "agriculture", "logistics"],
    relatedPosts: ["custom-erp-vs-ready-made-erp", "custom-software-vs-saas"],
    keywords: ["ERP software development", "custom ERP development", "ERP development company India"],
  },
  {
    slug: "hrms-development",
    name: "HRMS Development",
    navLabel: "HRMS Development",
    icon: "briefcase",
    pillar: true,
    seoTitle: "HRMS Development Company | HRMS & Payroll Software | FairBazaar",
    metaDescription:
      "HRMS and payroll software development: attendance, location-based attendance, leave, payroll, expenses, performance and HR analytics. Deploy FairBazaar HRMS or build a custom HR platform.",
    headline: "Your Entire Workforce. One Intelligent Platform.",
    intro:
      "Use FairBazaar HRMS as a ready platform, or have us customise and extend it for your policies, shift patterns, field teams and payroll rules.",
    answer: {
      question: "What is HRMS software?",
      text:
        "HRMS (Human Resource Management System) software manages the employee lifecycle in one platform: employee records, attendance, leave, payroll, expenses, performance and HR reporting. Modern HRMS platforms add mobile and location-based attendance, manager approval workflows and analytics so HR teams spend less time on manual administration.",
    },
    problems: [
      "Attendance collected on paper registers or spreadsheets",
      "Payroll calculated manually every month",
      "Field staff attendance that can't be verified",
      "Leave and expense approvals stuck in email threads",
    ],
    offerings: [
      { title: "FairBazaar HRMS Deployment", text: "Configure the FairBazaar HRMS platform for your organisation." },
      { title: "Custom HR Modules", text: "Policies, shift rules, allowances and workflows specific to you." },
      { title: "Location-based Attendance", text: "Geo-fenced mobile check-in for field and multi-site teams." },
      { title: "Payroll Integration", text: "Attendance-linked payroll with statutory components configured to your policies." },
      { title: "HR Analytics", text: "Headcount, attrition, attendance and cost dashboards." },
      { title: "Migration", text: "Move employee data from spreadsheets or legacy systems." },
    ],
    process: stdProcess,
    outcomes: [
      "Attendance and payroll in one connected flow",
      "Verified attendance for field and remote teams",
      "Faster approvals for leave and expenses",
      "HR data ready for decisions, not just records",
    ],
    technologies: ["Next.js", "React Native", "FastAPI", "PostgreSQL", "Geo-fencing APIs", "AWS"],
    faqs: [
      { q: "Do you provide HRMS software?", a: "Yes. FairBazaar HRMS covers employee management, attendance including location-based attendance, leave, holidays, payroll, expenses, invoices, performance, documents, reports and HR analytics." },
      { q: "Can HRMS be customised for our policies?", a: "Yes. Leave rules, shifts, approval chains, pay components and roles can be configured, and custom modules can be built where needed." },
      { q: "Does the HRMS have a mobile app?", a: "Yes. Employees can check in, apply for leave, submit expenses and view payslips from mobile." },
    ],
    relatedProducts: ["hrms"],
    relatedIndustries: ["manufacturing", "healthcare", "education", "logistics"],
    relatedPosts: ["what-is-hrms-software", "location-based-attendance-guide"],
    keywords: ["HRMS software", "HRMS development company", "payroll software India", "attendance management system"],
  },
  {
    slug: "business-automation",
    name: "Business Automation",
    navLabel: "Business Automation",
    icon: "workflow",
    seoTitle: "Business Process Automation Services & Software | FairBazaar",
    metaDescription:
      "Business automation software and services: workflows, approvals, notifications, integrations and AI automation that remove repetitive work across your organisation.",
    headline: "Remove the Work That Shouldn't Need a Person",
    intro:
      "We map your repetitive processes — approvals, data entry, notifications, reports — and automate them across the systems you already use.",
    answer: {
      question: "What is business process automation?",
      text:
        "Business process automation uses software to carry out repetitive, rule-based tasks such as approvals, data transfer between systems, notifications, document generation and reporting. It reduces manual effort and errors, speeds up processes, and frees staff to focus on work that needs judgement. Adding AI extends automation to unstructured inputs like emails and documents.",
    },
    problems: [
      "Copy-pasting data between systems",
      "Approvals delayed because nobody was notified",
      "Reports rebuilt manually every week",
      "Customer updates sent by hand",
    ],
    offerings: [
      { title: "Workflow Automation", text: "Multi-step processes with conditions, SLAs and escalations." },
      { title: "Approvals", text: "Configurable approval chains for purchases, leave, expenses and discounts." },
      { title: "Notifications", text: "Email, SMS, WhatsApp and in-app alerts triggered by events." },
      { title: "Integrations", text: "Connect CRM, ERP, HRMS, accounting, payment and messaging tools." },
      { title: "Document Generation", text: "Quotations, invoices, letters and reports generated automatically." },
      { title: "AI Automation", text: "Classify emails, extract document data and route requests with AI." },
    ],
    process: stdProcess,
    outcomes: ["Less manual data entry", "Faster cycle times for approvals", "Fewer errors from re-keying", "Consistent, trackable processes"],
    technologies: ["Python", "FastAPI", "Queues & schedulers", "Webhooks", "REST APIs", "LLMs", "PostgreSQL"],
    faqs: [
      { q: "What processes can be automated?", a: "Any repetitive, rule-based process: approvals, data syncing, notifications, report generation, invoice processing, onboarding checklists and more." },
      { q: "Do we need to replace our existing tools?", a: "No. Automation usually connects the tools you already use through their APIs." },
    ],
    relatedProducts: ["business-automation", "ai-agents"],
    relatedIndustries: ["smes", "finance", "logistics", "professional-services"],
    relatedPosts: ["ai-business-automation", "business-process-automation-guide"],
    keywords: ["business automation software", "business process automation services", "workflow automation India"],
  },
  {
    slug: "cloud-devops",
    name: "Cloud & DevOps",
    navLabel: "Cloud & DevOps",
    icon: "cloud",
    seoTitle: "Cloud & DevOps Services | AWS, Docker, CI/CD | FairBazaar",
    metaDescription:
      "Cloud deployment, migration, CI/CD pipelines, containerisation, monitoring and cost optimisation for business applications and SaaS products.",
    headline: "Infrastructure That Scales Quietly",
    intro:
      "Reliable deployments, automated pipelines and monitored infrastructure — so your software stays fast and available as usage grows.",
    answer: {
      question: "What are cloud and DevOps services?",
      text:
        "Cloud and DevOps services cover deploying applications to cloud infrastructure and automating how software is built, tested and released. This includes cloud architecture, migration, containerisation with Docker, CI/CD pipelines, monitoring, backups, security hardening and cost optimisation, so releases are frequent and reliable.",
    },
    problems: ["Manual, risky deployments", "Servers nobody monitors until they fail", "Cloud bills growing without visibility", "No backup or disaster recovery plan"],
    offerings: [
      { title: "Cloud Architecture", text: "Right-sized, secure infrastructure on AWS and other providers." },
      { title: "Migration", text: "Move legacy apps and databases to the cloud with minimal downtime." },
      { title: "CI/CD", text: "Automated build, test and deployment pipelines." },
      { title: "Containers", text: "Docker-based deployments for consistency across environments." },
      { title: "Monitoring & Backups", text: "Uptime, performance and error monitoring with automated backups." },
      { title: "Cost Optimisation", text: "Reduce spend through right-sizing and architecture changes." },
    ],
    process: stdProcess,
    outcomes: ["Repeatable, low-risk releases", "Visibility into performance and errors", "Predictable cloud costs", "Recovery plans that are tested"],
    technologies: ["AWS", "Docker", "GitHub Actions", "CI/CD", "Nginx", "PostgreSQL", "Monitoring & logging"],
    faqs: [
      { q: "Do you provide cloud deployment?", a: "Yes. We deploy and manage applications on cloud infrastructure, including CI/CD, monitoring and backups." },
      { q: "Can you migrate our existing application to the cloud?", a: "Yes. We assess the application, plan the migration and move it with testing and rollback plans." },
    ],
    relatedProducts: ["custom-business-software"],
    relatedIndustries: ["startups", "enterprise", "finance"],
    relatedPosts: ["cloud-migration-checklist"],
    keywords: ["cloud DevOps services", "AWS deployment services", "CI/CD setup"],
  },
  {
    slug: "ui-ux-design",
    name: "UI/UX Design",
    navLabel: "UI/UX Design",
    icon: "palette",
    seoTitle: "UI/UX Design Services for SaaS & Business Software | FairBazaar",
    metaDescription:
      "UI/UX design for SaaS products, dashboards, web and mobile apps: user research, information architecture, design systems and prototypes.",
    headline: "Software People Understand in Seconds",
    intro: "Complex business software doesn't have to be complicated to use. We design interfaces that reduce training time and errors.",
    answer: {
      question: "Why does UI/UX design matter for business software?",
      text:
        "Good UI/UX design makes business software faster to learn, quicker to use and less error-prone. For internal tools it reduces training time and support requests; for SaaS products it improves activation and retention. It covers research, information architecture, interaction design, visual design and design systems.",
    },
    problems: ["Staff avoiding a system because it is hard to use", "Long onboarding and training cycles", "Inconsistent screens across modules", "Low trial-to-paid conversion in SaaS"],
    offerings: [
      { title: "User Research", text: "Interviews and workflow observation with real users." },
      { title: "Information Architecture", text: "Navigation and data structures that match mental models." },
      { title: "Dashboard Design", text: "Data-dense screens that stay readable." },
      { title: "Design Systems", text: "Reusable components for consistent, faster delivery." },
      { title: "Prototyping", text: "Clickable prototypes validated before development." },
      { title: "Accessibility", text: "WCAG-conscious design for all users." },
    ],
    process: stdProcess,
    outcomes: ["Shorter training time", "Fewer user errors", "Consistent product experience", "Faster development from a shared design system"],
    technologies: ["Figma", "Design tokens", "React component libraries", "Accessibility audits"],
    faqs: [{ q: "Do you design existing software or only new products?", a: "Both. We redesign existing applications and design new products from scratch." }],
    relatedProducts: ["hrms", "crm"],
    relatedIndustries: ["startups", "enterprise"],
    relatedPosts: ["how-to-choose-a-software-development-company"],
    keywords: ["UI UX design services", "SaaS UI design", "dashboard design"],
  },
  {
    slug: "digital-transformation",
    name: "Digital Transformation",
    navLabel: "Digital Transformation",
    icon: "compass",
    pillar: true,
    seoTitle: "Digital Transformation Services for SMEs & Enterprises | FairBazaar",
    metaDescription:
      "Digital transformation services: process mapping, technology roadmaps, system modernisation, automation and AI adoption for growing businesses in India and beyond.",
    headline: "From Manual Operations to a Digital Business",
    intro:
      "Digital transformation isn't buying software — it's redesigning how work flows through your organisation. We help you plan it, build it and adopt it.",
    answer: {
      question: "What is digital transformation?",
      text:
        "Digital transformation is the process of redesigning a business's operations, customer experience and decision-making using digital technology. In practice it means replacing manual and paper-based processes with connected software, automating repetitive work, centralising data, and using analytics and AI to operate more efficiently and serve customers better.",
    },
    problems: ["Operations dependent on a few people's memory", "Paper, spreadsheets and messaging apps as core systems", "No reliable data for decisions", "Past software investments that were never adopted"],
    offerings: [
      { title: "Process Mapping", text: "Document current workflows and identify bottlenecks." },
      { title: "Technology Roadmap", text: "A phased plan prioritised by business impact." },
      { title: "System Modernisation", text: "Replace or upgrade legacy systems." },
      { title: "Automation & AI Adoption", text: "Introduce automation and AI where it pays back." },
      { title: "Data & Analytics", text: "Centralise data and build management dashboards." },
      { title: "Change Management", text: "Training and rollout plans that drive adoption." },
    ],
    process: stdProcess,
    outcomes: ["A clear, phased technology plan", "Processes that don't depend on individuals", "Data-driven management", "Software your team actually adopts"],
    technologies: ["CRM", "ERP", "HRMS", "Automation", "AI", "Cloud", "Analytics"],
    faqs: [
      { q: "Where should a small business start with digital transformation?", a: "Start with the process that costs the most time or causes the most errors — often sales follow-ups, inventory or attendance and payroll — and digitise it end to end before expanding." },
      { q: "Is digital transformation only for large enterprises?", a: "No. SMEs often see the fastest returns because a single connected system can replace several manual processes." },
    ],
    relatedProducts: ["erp", "crm", "hrms", "business-automation"],
    relatedIndustries: ["smes", "manufacturing", "agriculture", "enterprise"],
    relatedPosts: ["digital-transformation-for-smes", "ai-business-automation"],
    keywords: ["digital transformation services", "digital transformation for SMEs", "IT solutions company"],
  },
  {
    slug: "it-consulting",
    name: "IT Consulting",
    navLabel: "IT Consulting",
    icon: "clipboard",
    seoTitle: "IT Consulting Services | Technology Strategy & Architecture | FairBazaar",
    metaDescription:
      "IT consulting for technology selection, software architecture, build-vs-buy decisions, security reviews and product strategy for startups, SMEs and enterprises.",
    headline: "Technology Decisions, Made With Confidence",
    intro: "Independent advice on what to build, what to buy and how to architect it — before you commit budget.",
    answer: {
      question: "What does an IT consulting company do?",
      text:
        "An IT consulting company advises organisations on technology decisions: selecting software, designing system architecture, planning build-versus-buy choices, reviewing security, and creating implementation roadmaps. The goal is to reduce risk and cost by making informed decisions before investing in development or licences.",
    },
    problems: ["Uncertainty between building or buying software", "Vendor proposals that are hard to compare", "Architecture that won't scale", "Security gaps nobody has reviewed"],
    offerings: [
      { title: "Build vs Buy Analysis", text: "Compare SaaS options against custom development." },
      { title: "Architecture Review", text: "Assess scalability, reliability and maintainability." },
      { title: "Technology Selection", text: "Choose stacks and vendors that fit your team and budget." },
      { title: "Security Review", text: "Identify and prioritise application security risks." },
      { title: "Product Strategy", text: "MVP scoping and SaaS product roadmaps." },
      { title: "Vendor Evaluation", text: "Independent review of proposals and estimates." },
    ],
    process: stdProcess,
    outcomes: ["Lower risk on technology investments", "Clear architecture decisions", "Realistic roadmaps and budgets"],
    technologies: ["Architecture", "Security", "Cloud", "SaaS evaluation"],
    faqs: [{ q: "Can you review a proposal from another vendor?", a: "Yes. We provide independent reviews of scope, architecture and estimates." }],
    relatedProducts: ["custom-business-software"],
    relatedIndustries: ["startups", "enterprise", "smes"],
    relatedPosts: ["how-to-choose-a-software-development-company", "custom-software-vs-saas"],
    keywords: ["IT consulting services", "software architecture consulting", "technology consulting India"],
  },
];

export const getService = (slug: string) => services.find((s) => s.slug === slug);
